/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuItems;

import com.mycompany.intersisacotizador_ver2.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class ListadoCotizacionFrame extends javax.swing.JFrame {

    private static Connection con;
    private static Conexion conexion;
    public static int Num_cot = 0;
    
    public ListadoCotizacionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setLocation(getX(), 75);
        conexion = new Conexion();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbcliente = new javax.swing.JComboBox<>();
        cbetapa = new javax.swing.JComboBox<>();
        btnfiltrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbActivas = new javax.swing.JRadioButton();
        rbEtapa = new javax.swing.JRadioButton();
        rbInactivas = new javax.swing.JRadioButton();
        rbVendedor = new javax.swing.JRadioButton();
        rbCliente = new javax.swing.JRadioButton();
        cbvendedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvcoti = new javax.swing.JTable();
        btnVerEditar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnInactivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Listado de Cotizaciones");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Filtrar por:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Cliente");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Etapa");

        cbcliente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cbcliente.setEnabled(false);

        cbetapa.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cbetapa.setEnabled(false);

        btnfiltrar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnfiltrar.setText("Filtrar");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(rbActivas);
        rbActivas.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rbActivas.setSelected(true);
        rbActivas.setText("ACTIVAS");
        rbActivas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbActivasItemStateChanged(evt);
            }
        });

        rbEtapa.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rbEtapa.setText("Etapa");
        rbEtapa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbEtapaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbInactivas);
        rbInactivas.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rbInactivas.setForeground(new java.awt.Color(204, 0, 0));
        rbInactivas.setText("INACTIVAS");
        rbInactivas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbInactivasItemStateChanged(evt);
            }
        });

        rbVendedor.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rbVendedor.setText("Vendedor");
        rbVendedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbVendedorItemStateChanged(evt);
            }
        });

        rbCliente.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        rbCliente.setText("Cliente");
        rbCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbClienteItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(rbActivas)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(rbInactivas)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rbCliente)
                .addGap(18, 18, 18)
                .addComponent(rbEtapa)
                .addGap(18, 18, 18)
                .addComponent(rbVendedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbActivas)
                    .addComponent(rbInactivas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEtapa)
                    .addComponent(rbVendedor)
                    .addComponent(rbCliente))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        cbvendedor.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cbvendedor.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Vendedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(469, 469, 469)
                .addComponent(btnfiltrar)
                .addContainerGap(500, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbetapa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(cbvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cbetapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnfiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dgvcoti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ncot", "Fecha", "Clientes", "Etapa", "Descripción", "Vendedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dgvcoti);
        if (dgvcoti.getColumnModel().getColumnCount() > 0) {
            dgvcoti.getColumnModel().getColumn(0).setMinWidth(100);
            dgvcoti.getColumnModel().getColumn(0).setPreferredWidth(3);
            dgvcoti.getColumnModel().getColumn(0).setMaxWidth(100);
            dgvcoti.getColumnModel().getColumn(1).setMinWidth(100);
            dgvcoti.getColumnModel().getColumn(1).setPreferredWidth(5);
            dgvcoti.getColumnModel().getColumn(1).setMaxWidth(100);
            dgvcoti.getColumnModel().getColumn(2).setPreferredWidth(5);
            dgvcoti.getColumnModel().getColumn(3).setPreferredWidth(8);
        }

        btnVerEditar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnVerEditar.setText("Ver / Editar");
        btnVerEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEditarActionPerformed(evt);
            }
        });

        btnActivar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnActivar.setText("Reactivar");
        btnActivar.setEnabled(false);
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnInactivar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnInactivar.setText("Inactivar");
        btnInactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVerEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActivar)
                        .addGap(59, 59, 59)
                        .addComponent(btnInactivar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerEditar)
                    .addComponent(btnActivar)
                    .addComponent(btnInactivar))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modeloTabla = (DefaultTableModel) dgvcoti.getModel();
        modeloTabla.setRowCount(0);
        
        // Agrega los nombres de las columnas
        modeloTabla.setColumnIdentifiers(new Object[]{"NCot", "Fecha", "Cliente", "Etapa", "Descripción", "Vendedor"});
        
        String codsql = "";
        Object nombre1 = cbcliente.getSelectedItem();
        String nombreCli = nombre1.toString();
        Object nombre2 = cbetapa.getSelectedItem();
        String nombreEt = nombre2.toString();
        Object nombre3 = cbvendedor.getSelectedItem();
        String nombreVe = nombre3.toString();
        //---ACTIVAS---
        if(rbCliente.isSelected() && rbEtapa.isSelected() && rbActivas.isSelected() && rbVendedor.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 1 AND Clientes.Nombre='"+ nombreCli+ "' AND Etapa.Nombre='"+ nombreEt+ "' AND Cotizacion.Vendedor='"+ nombreVe+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbCliente.isSelected() && rbActivas.isSelected() && rbVendedor.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 1 AND Clientes.Nombre='"+ nombreCli+ "' AND Cotizacion.Vendedor='"+ nombreVe+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbEtapa.isSelected() && rbActivas.isSelected() && rbVendedor.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 1 AND Etapa.Nombre='"+ nombreEt+ "' AND Cotizacion.Vendedor='"+ nombreVe+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbCliente.isSelected() && rbEtapa.isSelected() && rbActivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 1 AND Clientes.Nombre='"+ nombreCli+ "' AND Etapa.Nombre='"+ nombreEt+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbCliente.isSelected() && rbActivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 1 AND Clientes.Nombre='"+ nombreCli+ "' order by Cotizacion.Id_Cotizacion Desc";
        }else if(rbEtapa.isSelected() && rbActivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 1 AND Etapa.Nombre='"+ nombreEt+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbVendedor.isSelected() && rbActivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 1 AND Cotizacion.Vendedor='"+ nombreVe+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbActivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 1 order by Cotizacion.Id_Cotizacion Desc";
        }
        //---INACTIVAS---
        if(rbCliente.isSelected() && rbEtapa.isSelected() && rbInactivas.isSelected() && rbVendedor.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 0 AND Clientes.Nombre='"+ nombreCli+ "' AND Etapa.Nombre='"+ nombreEt+ "' AND Cotizacion.Vendedor='"+ nombreVe+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbCliente.isSelected() && rbInactivas.isSelected() && rbVendedor.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 0 AND Clientes.Nombre='"+ nombreCli+ "' AND Cotizacion.Vendedor='"+ nombreVe+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbEtapa.isSelected() && rbInactivas.isSelected() && rbVendedor.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 0 AND Etapa.Nombre='"+ nombreEt+ "' AND Cotizacion.Vendedor='"+ nombreVe+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbCliente.isSelected() && rbEtapa.isSelected() && rbInactivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 0 AND Clientes.Nombre='"+ nombreCli+ "' AND Etapa.Nombre='"+ nombreEt+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbCliente.isSelected() && rbInactivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 0 AND Clientes.Nombre='"+ nombreCli+ "' order by Cotizacion.Id_Cotizacion Desc";
        }else if(rbEtapa.isSelected() && rbInactivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 0 AND Etapa.Nombre='"+ nombreEt+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbVendedor.isSelected() && rbInactivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 0 AND Cotizacion.Vendedor='"+ nombreVe+ "' order by Cotizacion.Id_Cotizacion Desc";
        }
        else if(rbInactivas.isSelected()){
            codsql = "select Cotizacion.Id_Cotizacion as NCot,Cotizacion.Fecha,Clientes.Nombre as Cliente,Etapa.Nombre as Etapa,Cotizacion.Descripcion, Cotizacion.Vendedor from Cotizacion inner join Etapa on Cotizacion.Id_Etapa=Etapa.Id_Etapa inner join Clientes on Cotizacion.Id_Cliente=Clientes.Id_Cliente where Cotizacion.Activo = 0 order by Cotizacion.Id_Cotizacion Desc";
        }
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        int[]anchos = {5,20,20,100,400,100};
        for(int i = 0; i < dgvcoti.getColumnCount(); i++){
            dgvcoti.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        
        try{
            con = conexion.establecerConexion();
            ps = con.prepareStatement(codsql);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; i++){
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
            
        }
    }//GEN-LAST:event_btnfiltrarActionPerformed

    private void rbInactivasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbInactivasItemStateChanged
        // TODO add your handling code here:
        if(rbInactivas.isSelected()){
            btnActivar.setEnabled(true);
        }else
        {
            btnActivar.setEnabled(false);
        }
    }//GEN-LAST:event_rbInactivasItemStateChanged

    private void rbActivasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbActivasItemStateChanged
        // TODO add your handling code here:
        if(rbActivas.isSelected()){
            btnInactivar.setEnabled(true);
        }else
        {
            btnInactivar.setEnabled(false);
        }
    }//GEN-LAST:event_rbActivasItemStateChanged

    private void rbEtapaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbEtapaItemStateChanged
        // TODO add your handling code here:
        if(rbEtapa.isSelected())
            cbetapa.setEnabled(true);
        else
            cbetapa.setEnabled(false);
    }//GEN-LAST:event_rbEtapaItemStateChanged

    private void rbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbClienteItemStateChanged
        // TODO add your handling code here:
        if(rbCliente.isSelected())
            cbcliente.setEnabled(true);
        else
            cbcliente.setEnabled(false);
    }//GEN-LAST:event_rbClienteItemStateChanged

    private void btnInactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = dgvcoti.getSelectedRow();
            int valor = Integer.parseInt(dgvcoti.getValueAt(selectedRow, dgvcoti.getColumnModel().getColumnIndex("NCot")).toString());

            int result = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar la cotización?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (result == JOptionPane.YES_OPTION) {
                PreparedStatement eliminar = con.prepareStatement("update Cotizacion set Activo = 0 where id_Cotizacion = ?");
                eliminar.setInt(1, valor);
                eliminar.executeUpdate();

                // Remove the row from the table
                ((DefaultTableModel) dgvcoti.getModel()).removeRow(selectedRow);
            }
        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInactivarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = dgvcoti.getSelectedRow();
            int valor = Integer.parseInt(dgvcoti.getValueAt(selectedRow, dgvcoti.getColumnModel().getColumnIndex("NCot")).toString());

            int result = JOptionPane.showConfirmDialog(null, "Esta seguro que desea reactivar la cotización?", "Reactivar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (result == JOptionPane.YES_OPTION) {
                PreparedStatement eliminar = con.prepareStatement("update Cotizacion set Activo = 1 where id_Cotizacion = ?");
                eliminar.setInt(1, valor);
                eliminar.executeUpdate();

                // Remove the row from the table
                ((DefaultTableModel) dgvcoti.getModel()).removeRow(selectedRow);
            }
        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void rbVendedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbVendedorItemStateChanged
        // TODO add your handling code here:
        if(rbVendedor.isSelected())
            cbvendedor.setEnabled(true);
        else
            cbvendedor.setEnabled(false);
    }//GEN-LAST:event_rbVendedorItemStateChanged

    private void btnVerEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEditarActionPerformed
        // TODO add your handling code here:
        int selectedRow = dgvcoti.getSelectedRow();
        if(selectedRow != -1){
            int valor = Integer.parseInt(dgvcoti.getValueAt(selectedRow, 0).toString());
            Num_cot = valor;
            ModificarCotizacionFrame mcf = new ModificarCotizacionFrame();
            mcf.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Seleccione una cotización para modificar");
        }
    }//GEN-LAST:event_btnVerEditarActionPerformed

    private void cargarDatos(){
        
        PreparedStatement ps, ps1, ps2;
        ResultSet rs, rs1, rs2;
         try {
            con = conexion.establecerConexion();

            if (cbcliente != null) {
                ps = con.prepareStatement("SELECT * FROM Clientes ORDER BY Nombre ASC");
                ps1 = con.prepareStatement("SELECT * FROM Etapa ORDER BY Nombre ASC");
                ps2 = con.prepareStatement("SELECT DISTINCT Vendedor FROM Cotizacion WHERE Vendedor IS NOT NULL ORDER BY Vendedor ASC");
                rs = ps.executeQuery();               
                rs1 = ps1.executeQuery();       
                rs2 = ps2.executeQuery();

                // Create a new DefaultComboBoxModel to replace the existing one
                DefaultComboBoxModel<String> newModel = new DefaultComboBoxModel<>();
                DefaultComboBoxModel<String> newMode11 = new DefaultComboBoxModel<>();
                DefaultComboBoxModel<String> newMode12 = new DefaultComboBoxModel<>();

                while (rs.next()) {
                    newModel.addElement(rs.getString("Nombre")); 
                }
                while (rs1.next()){
                    newMode11.addElement(rs1.getString("Nombre"));
                }
                while (rs2.next()){
                    newMode12.addElement(rs2.getString("Vendedor"));
                }

                // Set the new model to the JComboBox
                cbcliente.setModel(newModel);
                cbetapa.setModel(newMode11);
                cbvendedor.setModel(newMode12);

                rs.close();
                rs1.close();
                rs2.close();
            } else {
                JOptionPane.showMessageDialog(null, "Error: cbcliente is null");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoCotizacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoCotizacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoCotizacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoCotizacionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoCotizacionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnInactivar;
    private javax.swing.JButton btnVerEditar;
    private javax.swing.JButton btnfiltrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbcliente;
    private javax.swing.JComboBox<String> cbetapa;
    private javax.swing.JComboBox<String> cbvendedor;
    private javax.swing.JTable dgvcoti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbActivas;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JRadioButton rbEtapa;
    private javax.swing.JRadioButton rbInactivas;
    private javax.swing.JRadioButton rbVendedor;
    // End of variables declaration//GEN-END:variables
}
