
import MenuItems.AltaMateriaPrimaFrame;
import MenuItems.ClientesFrame;
import MenuItems.EtapasFrame;
import MenuItems.ListadoCotizacionFrame;
import MenuItems.ListadoMateriaPrimaFrame;
import MenuItems.NuevaCotizacionFrame;
import MenuItems.PreciosFrame;
import MenuItems.UsuariosFrame;
import MenuItems.VendedoresFrame;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    Font fontIn = new Font("Segoe UI", Font.PLAIN, 20);
    Font fontOut = new Font("Segoe UI", Font.PLAIN, 18);
    
    public MenuFrame() {
        initComponents();
        pack();
        //setSize(1050, 1000);
        setResizable(false);
        setLocationRelativeTo(null);
        setLocation(getX(), 5);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/appicon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelContent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCotizaciones = new javax.swing.JMenu();
        jMenuItemNuevaCotizacion = new javax.swing.JMenuItem();
        jMenuItemListado = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAltaMateriaPrima = new javax.swing.JMenuItem();
        jMenuItemListadoMateriaPrima = new javax.swing.JMenuItem();
        jMenuEtapas = new javax.swing.JMenu();
        jMenuPrecios = new javax.swing.JMenu();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuVendedores = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1070, 700));

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner.png"))); // NOI18N

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(0, 88, 0, 0));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(398, 45));

        jMenuCotizaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cotizaciones.png"))); // NOI18N
        jMenuCotizaciones.setText("Cotizaciones");
        jMenuCotizaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuCotizaciones.setMaximumSize(new java.awt.Dimension(150, 32767));
        jMenuCotizaciones.setPreferredSize(new java.awt.Dimension(150, 40));
        jMenuCotizaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCotizacionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuCotizacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuCotizacionesMouseExited(evt);
            }
        });

        jMenuItemNuevaCotizacion.setText("Nueva Cotización");
        jMenuItemNuevaCotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemNuevaCotizacionMouseClicked(evt);
            }
        });
        jMenuItemNuevaCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaCotizacionActionPerformed(evt);
            }
        });
        jMenuCotizaciones.add(jMenuItemNuevaCotizacion);

        jMenuItemListado.setText("Listado");
        jMenuItemListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoActionPerformed(evt);
            }
        });
        jMenuCotizaciones.add(jMenuItemListado);

        jMenuBar1.add(jMenuCotizaciones);

        jMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes.png"))); // NOI18N
        jMenuClientes.setText("Clientes");
        jMenuClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuClientes.setHideActionText(true);
        jMenuClientes.setMaximumSize(new java.awt.Dimension(110, 32767));
        jMenuClientes.setPreferredSize(new java.awt.Dimension(160, 30));
        jMenuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuClientesMouseExited(evt);
            }
        });
        jMenuBar1.add(jMenuClientes);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materias_primas.png"))); // NOI18N
        jMenu3.setText("Materia Prima");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu3MouseExited(evt);
            }
        });

        jMenuItemAltaMateriaPrima.setText("Alta Materia Prima");
        jMenuItemAltaMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaMateriaPrimaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAltaMateriaPrima);

        jMenuItemListadoMateriaPrima.setText("Listado Materia Prima");
        jMenuItemListadoMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoMateriaPrimaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemListadoMateriaPrima);

        jMenuBar1.add(jMenu3);

        jMenuEtapas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etapas.png"))); // NOI18N
        jMenuEtapas.setText("Etapas");
        jMenuEtapas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuEtapas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEtapasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuEtapasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuEtapasMouseExited(evt);
            }
        });
        jMenuEtapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEtapasActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuEtapas);

        jMenuPrecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/precios.png"))); // NOI18N
        jMenuPrecios.setText("Precios");
        jMenuPrecios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuPrecios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPreciosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuPreciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuPreciosMouseExited(evt);
            }
        });
        jMenuBar1.add(jMenuPrecios);

        jMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuarios.png"))); // NOI18N
        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuUsuariosMouseExited(evt);
            }
        });
        jMenuBar1.add(jMenuUsuarios);

        jMenuVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendedores.png"))); // NOI18N
        jMenuVendedores.setText("Vendedores");
        jMenuVendedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuVendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVendedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuVendedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuVendedoresMouseExited(evt);
            }
        });
        jMenuVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendedoresActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuVendedores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 100, 1086, 739);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItemNuevaCotizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemNuevaCotizacionMouseClicked
        // TODO add your handling coPrincipalFrame pf = new PrincipalFrame();
        /*PrincipalFrame pf = new PrincipalFrame();
        JPanelContainer.removeAll();
        JPanelContainer.add(pf).setVisible(true);*/
    }//GEN-LAST:event_jMenuItemNuevaCotizacionMouseClicked

    private void jMenuItemNuevaCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaCotizacionActionPerformed
        // TODO add your handling code here:
        NuevaCotizacionFrame ncf = new NuevaCotizacionFrame();
        ncf.setVisible(true);
        setSize(1070,85);
    }//GEN-LAST:event_jMenuItemNuevaCotizacionActionPerformed

    private void jMenuCotizacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCotizacionesMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuCotizacionesMouseClicked

    private void jMenuItemListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoActionPerformed
        // TODO add your handling code here:
        ListadoCotizacionFrame lcf = new ListadoCotizacionFrame();
        lcf.setVisible(true);
        setSize(1070,85);
        
    }//GEN-LAST:event_jMenuItemListadoActionPerformed

    private void jMenuItemAltaMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaMateriaPrimaActionPerformed
        // TODO add your handling code here:
        AltaMateriaPrimaFrame ampf = new AltaMateriaPrimaFrame();
        ampf.setVisible(true);
        setSize(1070,85);
    }//GEN-LAST:event_jMenuItemAltaMateriaPrimaActionPerformed

    private void jMenuItemListadoMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoMateriaPrimaActionPerformed
        // TODO add your handling code here:
        ListadoMateriaPrimaFrame lmpf = new ListadoMateriaPrimaFrame();
        lmpf.setVisible(true);
        setSize(1070,85);
    }//GEN-LAST:event_jMenuItemListadoMateriaPrimaActionPerformed

    private void jMenuEtapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEtapasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEtapasActionPerformed

    private void jMenuEtapasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEtapasMouseClicked
        // TODO add your handling code here:
        EtapasFrame ef = new EtapasFrame();
        ef.setVisible(true);
        setSize(1070,85);
    }//GEN-LAST:event_jMenuEtapasMouseClicked

    private void jMenuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClientesMouseClicked
        // TODO add your handling code here:
        ClientesFrame cf = new ClientesFrame();
        cf.setVisible(true);
        setSize(1070,85);
    }//GEN-LAST:event_jMenuClientesMouseClicked

    private void jMenuPreciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPreciosMouseClicked
        // TODO add your handling code here:
        PreciosFrame pf = new PreciosFrame();
        pf.setVisible(true);
        setSize(1070,85);
    }//GEN-LAST:event_jMenuPreciosMouseClicked

    private void jMenuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsuariosMouseClicked
        // TODO add your handling code here:
        UsuariosFrame uf = new UsuariosFrame();
        uf.setVisible(true);
        setSize(1070,85);
    }//GEN-LAST:event_jMenuUsuariosMouseClicked

    private void jMenuCotizacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCotizacionesMouseEntered
        // TODO add your handling code here:
        jMenuCotizaciones.setFont(fontIn);
        jMenuCotizaciones.setOpaque(true);
        jMenuCotizaciones.setBackground(Color.lightGray);
    }//GEN-LAST:event_jMenuCotizacionesMouseEntered

    private void jMenuCotizacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCotizacionesMouseExited
        // TODO add your handling code here:
        jMenuCotizaciones.setFont(fontOut);
        jMenuCotizaciones.setOpaque(false);
        jMenuCotizaciones.setBackground(Color.white);
    }//GEN-LAST:event_jMenuCotizacionesMouseExited

    private void jMenuClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClientesMouseEntered
        // TODO add your handling code here:
        jMenuClientes.setFont(fontIn);
        jMenuClientes.setOpaque(true);
        jMenuClientes.setBackground(Color.lightGray);
    }//GEN-LAST:event_jMenuClientesMouseEntered

    private void jMenuClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClientesMouseExited
        // TODO add your handling code here:
        jMenuClientes.setFont(fontOut);
        jMenuClientes.setOpaque(false);
        jMenuClientes.setBackground(Color.white);
    }//GEN-LAST:event_jMenuClientesMouseExited

    private void jMenu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseEntered
        // TODO add your handling code here:
        jMenu3.setFont(fontIn);
        jMenu3.setOpaque(true);
        jMenu3.setBackground(Color.lightGray);
    }//GEN-LAST:event_jMenu3MouseEntered

    private void jMenu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseExited
        // TODO add your handling code here:
        jMenu3.setFont(fontOut);
        jMenu3.setOpaque(false);
        jMenu3.setBackground(Color.white);
    }//GEN-LAST:event_jMenu3MouseExited

    private void jMenuEtapasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEtapasMouseEntered
        // TODO add your handling code here:
        jMenuEtapas.setFont(fontIn);
        jMenuEtapas.setOpaque(true);
        jMenuEtapas.setBackground(Color.lightGray);
    }//GEN-LAST:event_jMenuEtapasMouseEntered

    private void jMenuEtapasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEtapasMouseExited
        // TODO add your handling code here:
        jMenuEtapas.setFont(fontOut);
        jMenuEtapas.setOpaque(false);
        jMenuEtapas.setBackground(Color.white);
    }//GEN-LAST:event_jMenuEtapasMouseExited

    private void jMenuPreciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPreciosMouseEntered
        // TODO add your handling code here:
        jMenuPrecios.setFont(fontIn);
        jMenuPrecios.setOpaque(true);
        jMenuPrecios.setBackground(Color.lightGray);
    }//GEN-LAST:event_jMenuPreciosMouseEntered

    private void jMenuPreciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPreciosMouseExited
        // TODO add your handling code here:
        jMenuPrecios.setFont(fontOut);
        jMenuPrecios.setOpaque(false);
        jMenuPrecios.setBackground(Color.white);
    }//GEN-LAST:event_jMenuPreciosMouseExited

    private void jMenuUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsuariosMouseEntered
        // TODO add your handling code here:
        jMenuUsuarios.setFont(fontIn);
        jMenuUsuarios.setOpaque(true);
        jMenuUsuarios.setBackground(Color.lightGray);
    }//GEN-LAST:event_jMenuUsuariosMouseEntered

    private void jMenuUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsuariosMouseExited
        // TODO add your handling code here:
        jMenuUsuarios.setFont(fontOut);
        jMenuUsuarios.setOpaque(false);
        jMenuUsuarios.setBackground(Color.white);
    }//GEN-LAST:event_jMenuUsuariosMouseExited

    private void jMenuVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuVendedoresActionPerformed

    private void jMenuVendedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVendedoresMouseEntered
        // TODO add your handling code here:
        jMenuVendedores.setFont(fontIn);
        jMenuVendedores.setOpaque(true);
        jMenuVendedores.setBackground(Color.lightGray);
    }//GEN-LAST:event_jMenuVendedoresMouseEntered

    private void jMenuVendedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVendedoresMouseExited
        // TODO add your handling code here:
        jMenuVendedores.setFont(fontOut);
        jMenuVendedores.setOpaque(false);
        jMenuVendedores.setBackground(Color.white);
    }//GEN-LAST:event_jMenuVendedoresMouseExited

    private void jMenuVendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVendedoresMouseClicked
        // TODO add your handling code here:
        VendedoresFrame vf = new VendedoresFrame();
        vf.setVisible(true);
        setSize(1070,85);
    }//GEN-LAST:event_jMenuVendedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuCotizaciones;
    private javax.swing.JMenu jMenuEtapas;
    private javax.swing.JMenuItem jMenuItemAltaMateriaPrima;
    private javax.swing.JMenuItem jMenuItemListado;
    private javax.swing.JMenuItem jMenuItemListadoMateriaPrima;
    private javax.swing.JMenuItem jMenuItemNuevaCotizacion;
    private javax.swing.JMenu jMenuPrecios;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JMenu jMenuVendedores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContent;
    // End of variables declaration//GEN-END:variables
}
